name: Release

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: delete Release and Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: "development"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Development Tag
        uses: "richardsimko/update-tag@v1"
        with:
          tag_name: "development"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Development Release
        uses: "ncipollo/release-action@v1"
        with:
          tag: "development"
          prerelease: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
