name: Ubuntu

on: [push]

jobs:
  verify-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup libraries
      run: |
        sudo apt update
        sudo apt-get install xorg-dev

    - name: Configure
      run: cmake -Brelease -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cd release && make

    - name: Test
      run: cd release && make test

    - name: Package
      run: cd release/bin && tar cvfz ../../ubuntu.tgz ot

    - name: Release
      uses: "svenstaro/upload-release-action@v2"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "development"
        file: ubuntu.tgz
        overwrite: true
