name: Ubuntu

on: [push]

jobs:
  verify-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup libuv
      run: sudo apt-get install libuv1-dev

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '3.22.x'

    - name: Configure
      run: mkdir build && cd build && cmake ..

    - name: Build
      run: cmake --build build

    - name: Test
      run: cd build && ctest
