name: Windows

on: [push]

jobs:
  verify-windows:
    runs-on: windows-2022
    name: build x64 on Windows 2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '3.22.x'

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure
