name: Windows

on: [push]

jobs:
  verify-windows:
    runs-on: windows-${{ matrix.config.server }}
    name: build-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019}
          - {toolchain: Visual Studio 17 2022, arch: x64, server: 2022}

    steps:
    - uses: actions/checkout@v2

    - name: Setup cmake
      uses: "jwlawson/actions-setup-cmake@v1.12"
      with:
        cmake-version: "3.22.x"

    - name: Setup zip
      uses: "montudor/action-zip@latest"

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}

    - name: Build
      run: cmake --build build -DCMAKE_BUILD_TYPE=Release

    - name: Package
      run: zip -qq -r windows.zip ot.exe
      working-directory: build/bin

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: windows.zip

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure
