name: Windows

on: [push]

jobs:
  verify-windows:
    runs-on: windows-${{ matrix.config.server }}
    name: build-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019}
          - {toolchain: Visual Studio 17 2022, arch: x64, server: 2022}

    steps:
    - uses: actions/checkout@v2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '3.19.x'

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure
